FROM ubuntu
RUN apt-get update -y
RUN apt-get install -y git && apt-get install -y gcc && apt-get install -y libncurses5-dev libncursesw5-dev && apt-get install -y build-essential
RUN git clone https://github.com/alt-romes/programmer-calculator
WORKDIR programmer-calculator
RUN make
